.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" This is free software; see the GNU General Public Licence version 2
.\" or later for copying conditions.  There is NO warranty.
.TH bugz 1 "10 Mar 2016" "1.0.0"
.nh
.SH NAME
bugz \(em command line interface to bugzilla
.SH SYNOPSIS
.B bugz
[
.B global options
]
.B subcommand
[
.B subcommand options
]
.\" .SH OPTIONS
.\" .TP
.\" .B \-o value, \-\^\-long=value
.\" Describe the option.
.SH DESCRIPTION
Bugz is a program which gives you access to the features of the
bugzilla bug tracking system from the command line.
.PP
This man page is a stub; the bugz program has extensive built in help.
.B bugz -h
will show the help for the global options and
.B bugz [subcommand] -h
will show the help for a specific subcommand.
.SH BUGS
.PP
The home page of this project is https://github.com/chuckliu1979/bugz.
Bugs should be reported to the bug tracker there.
.\" .SH SEE ALSO
.\" .PP
.SH AUTHOR
.PP
This man page is derived from https://github.com/williamh/pybugz
The original author is Alastair Tse <alastair@liquidx.net>.
The current maintainer for pybugz is William Hubbs <w.d.hubbs@gmail.com>.
William also wrote pybugz man page.
